application: 1010-charitable-trust
version: 1
runtime: python
api_version: 1

handlers:
- url: /mytag
  #script: split_test.py
  script: redirect.py

- url: /(.+\.(css|js|jpg|png|swf))
  static_files: \1
  upload: .+\.(css|js|jpg|png|swf)
